server:
  port: 0                            # 0?? ?? ?? ??? ?? ?? ??

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: search-service              # Eureka? ??? ??? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.xyz:3322/moviedb
    username: smile
    password: smile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#jwt:
#  secret: <??? Base64 ???? ??? ?>
#  expiration: 1800000          # access token ??(???)
#  refresh-expiration: 604800000  # refresh token ??(???)