server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:backend20250319/BE09-3rd-4team-private.git
          ignoreLocalSshSettings: true
          privatKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKgIBAAKCAgEAvPYZtvQ9q7abIX7FmFo8zLcGqUtDWmK005QXda6oOTk5QsNF
            wAyhAH/bgOKr8a8opgtquZzbpm66lzKd6C/GE+gigbc3gS+U154E/ge+EBmwdQNM
            uLacKFP2i3IhCs/6xNe1DBNhGg1HmuTiuPI3uVLm8dypTESn2VzE2cMQkV8u3pCn
            +2tbcZLYl5a/22rKoxUN/uqdWhFxg30fXJfbdzHvUw+YZeo1g8P2nFriLXJyDJhx
            0UESail4hY0/4LFqEkr8tS6uDI/5cj+yGa3gaghnqMmNxTKBRd/+pJTDyL8CL/78
            QfQ3e6rmhtKlQR+vlYWyrXFy2RNO6SuU67by58r+N8rFdWUGvXtUbwvqn5KsshFn
            y5SLNvB+ny54TFhQmSZdmG6EENVStRofqapnVoSycM5kmtvxcRHRW0rXc5HyqZmp
            ysGT5MeHeIh9hw7lJO9bjO8UDuzztvQkF0czKgLJufiJ/HKcalwxRx/PllEy0Pkh
            yzNoUIekdRpEaLOhbsgsezBJVEYKoB7e5VhlAiybALKlH+1Mt8OE0tOGGKKlleen
            Bmz2nO3B6xYAZ0EIxRaqQR118ycVxk85o0n47HiB/8DXBh0OvrGRcj74gto4uzjl
            oBEOWdO0XipXprJ/J5LUSssvFqhF/12WcCWfFN3ZuZ8ySnO4Y0Cfg6N5RyECAwEA
            AQKCAgEAtWDZAAdjZv7J25XvHzWG5M3ORBRtW0Yh4nFlL13uNbda4l3EBvtYU71m
            uklZ2IxUTUXqNK5/HDtvOZCph+TLkfIhpTdzvLoqeelBS4GtC5FNEpSPQUJvlDo8
            DlAHrXRDdkzDiQrVCweyMtj/U52UpXwRGBnCG+ZO41Kr1Ybq0U93EsXxqGC9jr/w
            zVkzYe8ZAP9Fxun3DixuNFOXFe7iB4DUA3uVwkXVBlzEzAJk1lDjbnmpzr1SarrR
            6AfUR96kPVjjRxq+kGpmeybu0r1XCxB0R8zoG2BGPActS1dMstW9yMpN4xUDaN57
            lvB9FYzPoouKHfgm0H07Io/ly3h5oSI/IV7D/NPyeZbH8myoMV619Ia8awQ47e7m
            PU55+0M6g7ngAkuxE0drPzsUmmT8dV765KUvSQVdbscfpvo2jHfkNRRp3xxC1tF+
            Q2KNKUWOsf+xLpBoK6AiaE5uk+musmAssSlYYFWQadqFi9+kXuMdAf2GoU3mbdtk
            T+Ro+F6zJSbO7XErl1R/9XWCkrXLqGHyfUaNF6nw5l9p+fSNAH1WiczlEScauC+T
            aUYkfYD+WVwX63R44DXcQ8Q9WjEpKQCPfjF4+uTcW5G61GRt476C0ouw9OoQ6LKj
            3emDAITCZgi6nI5yjZnKYr3PK+p2aaecye/7pdOiIYTRGtbaSAECggEBAPUViFOF
            kwPtWg3bHFf1LFQlC2s30EEewxgxfIbkMS95VoNwNJqb02uBu7ya+FUOeKKG4cEy
            zBfvlbl7YJNgcbipCqBwYcSZNNrfocyz4LbVCnP3ZMXlGEbCcK8qHDePe3J32H54
            w+08AU6Lj7FOxx2JSs8cUPz61bujv9mt1wGyOSNUdHaXmc3Ygwr7uGlB/ZWonYKw
            GX9AyB87xykqfJvI5YwulMeUPQnYt5805WyUOFymjb2664bjSXOQiLXPMOsJXbza
            PoUYCw1f9eP+22lLyOlMBDsfRta5qt45QNCS7+noLwMkFSSL7oYjhNtaUtUS8+Ju
            qh3ZE9NRwul9beECggEBAMVgptjXw4Q3vI19lT61vfb4cb83D0J+p54n1WA/R0e6
            sU4NA2oWI9BuP9wjLWwXmDY8nqIia4lRtDG39+raNOYbmmvap1xiggkQgLSARfq5
            mZMwXg0E/6hm7uCp7qf8m70f8EHRA3aOd55JtSXckgPRSWeDWQLv9xBYYlyekyD9
            LC/EolOLrTHGpXs4Uh2a2xcqQbctTSU6kTUtrkW6OaUwnRYiiFQnTO/6iJyrtaMA
            2Synuk6JHVZueUIw7PlPGihMITyFK+hMc9TOUM1y9xNVOisGgINR14W+pxVOl8q0
            4ZbkTEkZPJxFIGYEGorlHK2fNvKcAaXysVKz85qCgUECggEBAJAZYfdhsSf89Rby
            fn7E25R513Xp8htnv+PIrOQO5VB5ckGDxpolBrDOLZjeMSaphIpi7fePK2rjZlAR
            V54vdY3SbjoY+ZMDVY1fMZ3PIU++gQ/gJLMqWRS5nFGRW9fbGAUcrADodqJUxpvs
            +MaSgAZAw+h0SLYFsYdK5zFQwfrwVCIOtQ9JYZgjNiFOEYZp03ScGEhPzB4C8+dR
            WW892NgrzbOXa8jQwva4InaMPlyR5XWsQ+iLL5I2rugw0gC72pJHBoNUeq/8i/sI
            MeYk4dLOSUnKdS5h3F/B+NICLba0vjT0XDfnjjrXv53E4oeqWsuHAjhfQsyb5sk3
            6HcqVWECggEAH4CZoKpvTj8HHR4aH/Qp6a0lmntTOC222wtIhyASZGRrwCVbkicO
            eEngb2Y97a6mYKG0P/R2bWhY9kaCjz1cjA2DzAsOAzTFxGSZ5jVC9g2BcXiaykEt
            /NbQ8ZKtwKoUwU7Drf2KK/X5KY5iFzTpKSrSKG9SWaGrMTSqHlZA7Vb7InSj4+m7
            LuKhrtUCZi89IKlh67aTRYnfezlbQ03BvZfQuqOwVp4fLX4zJ65QQz/zaakrlzVT
            NWRUfjgI2pHBfwUHmP04UM9C/YggZWof/TnxGsTi5hK9717KlCADIhtUlhzCADjC
            774ouZ+WDO0ccqmiv34e1TmzC5wlGVgTAQKCAQEAg36eCRlBzh6/ED68sMst/TbP
            hfqX4NJ1Ls/kgRvvXGOAvCKWKs71Btjac03E71vp4j+xBzT5ZjUtwsNXjyTDSisk
            aQfnSY6J8jzzdtPWFMU6RSlBP8ilFIv8oCilzcUPET+m0nO+qXAy7HtUfaC7n83r
            vm886IR5/roSr5RQ/4qJxSbZAvCazJ1fMAEKxpUAaRpVare/+cFxO1xQz47FJXhI
            A0dHNexzYiJd6p02tyA+dAwawOBi3hD6loqT+ggixP6WFB08Xkj9O3EpMlkBSSXY
            pF88kORL5fVUV5imQspA4pfdTttR1e1XverFB0+wJ4c63hkBx89BNHUUFxoFxw==
            -----END RSA PRIVATE KEY-----